package com.wistron.swpc.android.WiTMJ.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.wistron.swpc.android.WiTMJ.bean.Navigation;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NAVIGATION".
*/
public class NavigationDao extends AbstractDao<Navigation, Long> {

    public static final String TABLENAME = "NAVIGATION";

    /**
     * Properties of entity Navigation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property Tag = new Property(2, Integer.class, "tag", false, "TAG");
        public final static Property StartRoute = new Property(3, String.class, "startRoute", false, "START_ROUTE");
        public final static Property EndRoute = new Property(4, String.class, "endRoute", false, "END_ROUTE");
    };


    public NavigationDao(DaoConfig config) {
        super(config);
    }
    
    public NavigationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NAVIGATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT NOT NULL ," + // 1: userId
                "\"TAG\" INTEGER," + // 2: tag
                "\"START_ROUTE\" TEXT," + // 3: startRoute
                "\"END_ROUTE\" TEXT);"); // 4: endRoute
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NAVIGATION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Navigation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getUserId());
 
        Integer tag = entity.getTag();
        if (tag != null) {
            stmt.bindLong(3, tag);
        }
 
        String startRoute = entity.getStartRoute();
        if (startRoute != null) {
            stmt.bindString(4, startRoute);
        }
 
        String endRoute = entity.getEndRoute();
        if (endRoute != null) {
            stmt.bindString(5, endRoute);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Navigation readEntity(Cursor cursor, int offset) {
        Navigation entity = new Navigation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // tag
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // startRoute
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // endRoute
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Navigation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getString(offset + 1));
        entity.setTag(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setStartRoute(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEndRoute(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Navigation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Navigation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
