package com.wistron.swpc.android.WiTMJ.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.wistron.swpc.android.WiTMJ.bean.WorkOut;

import com.wistron.swpc.android.WiTMJ.bean.Participants;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PARTICIPANTS".
*/
public class ParticipantsDao extends AbstractDao<Participants, Long> {

    public static final String TABLENAME = "PARTICIPANTS";

    /**
     * Properties of entity Participants.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property User_id = new Property(1, String.class, "user_id", false, "USER_ID");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Invitation = new Property(3, String.class, "invitation", false, "INVITATION");
        public final static Property Record_id = new Property(4, String.class, "record_id", false, "RECORD_ID");
        public final static Property Workout_id = new Property(5, String.class, "workout_id", false, "WORKOUT_ID");
    };

    private DaoSession daoSession;

    private Query<Participants> workOut_ParticipantsQuery;

    public ParticipantsDao(DaoConfig config) {
        super(config);
    }
    
    public ParticipantsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PARTICIPANTS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: user_id
                "\"USERNAME\" TEXT," + // 2: username
                "\"INVITATION\" TEXT," + // 3: invitation
                "\"RECORD_ID\" TEXT," + // 4: record_id
                "\"WORKOUT_ID\" TEXT);"); // 5: workout_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PARTICIPANTS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Participants entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindString(2, user_id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String invitation = entity.getInvitation();
        if (invitation != null) {
            stmt.bindString(4, invitation);
        }
 
        String record_id = entity.getRecord_id();
        if (record_id != null) {
            stmt.bindString(5, record_id);
        }
 
        String workout_id = entity.getWorkout_id();
        if (workout_id != null) {
            stmt.bindString(6, workout_id);
        }
    }

    @Override
    protected void attachEntity(Participants entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Participants readEntity(Cursor cursor, int offset) {
        Participants entity = new Participants( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // user_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // username
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // invitation
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // record_id
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // workout_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Participants entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUser_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUsername(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setInvitation(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setRecord_id(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWorkout_id(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Participants entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Participants entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "participants" to-many relationship of WorkOut. */
    public List<Participants> _queryWorkOut_Participants(String workout_id) {
        synchronized (this) {
            if (workOut_ParticipantsQuery == null) {
                QueryBuilder<Participants> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Workout_id.eq(null));
                workOut_ParticipantsQuery = queryBuilder.build();
            }
        }
        Query<Participants> query = workOut_ParticipantsQuery.forCurrentThread();
        query.setParameter(0, workout_id);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getWorkOutDao().getAllColumns());
            builder.append(" FROM PARTICIPANTS T");
            builder.append(" LEFT JOIN WORK_OUT T0 ON T.\"WORKOUT_ID\"=T0.\"WORKOUT_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Participants loadCurrentDeep(Cursor cursor, boolean lock) {
        Participants entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        WorkOut workOut = loadCurrentOther(daoSession.getWorkOutDao(), cursor, offset);
        entity.setWorkOut(workOut);

        return entity;    
    }

    public Participants loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Participants> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Participants> list = new ArrayList<Participants>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Participants> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Participants> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
