package com.example;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS


/**
 * Entity mapped to table "RECORDS".
 */
public class Records {

    // KEEP INCLUDES - put your custom includes here
    @SerializedName("_id")
    private Long id;
    @SerializedName("id")
    private String record_id;
    private String workout_id;
    private Integer tag;

    @Expose
    private java.util.Date start_time;
    @Expose
    private java.util.Date end_time;
    @Expose
    private Double duration;
    @Expose
    private Double distance;
    @Expose
    private Double calories;
    @Expose
    private Double avg_speed;
    @Expose
    private Integer rank;

    private Integer invitation;

    private String routes;
    // KEEP INCLUDES END


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Records() {
    }

    public Records(Long id) {
        this.id = id;
    }

    public Records(Long id, String record_id, String workout_id, Integer tag, java.util.Date start_time, java.util.Date end_time, Double duration, Double distance, Double calories, Double avg_speed, String routes, Integer rank, Integer invitation) {
        this.id = id;
        this.record_id = record_id;
        this.workout_id = workout_id;
        this.tag = tag;
        this.start_time = start_time;
        this.end_time = end_time;
        this.duration = duration;
        this.distance = distance;
        this.calories = calories;
        this.avg_speed = avg_speed;
        this.routes = routes;
        this.rank = rank;
        this.invitation = invitation;
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRecord_id() {
        return record_id;
    }

    public void setRecord_id(String record_id) {
        this.record_id = record_id;
    }

    public String getWorkout_id() {
        return workout_id;
    }

    public void setWorkout_id(String workout_id) {
        this.workout_id = workout_id;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public java.util.Date getStart_time() {
        return start_time;
    }

    public void setStart_time(java.util.Date start_time) {
        this.start_time = start_time;
    }

    public java.util.Date getEnd_time() {
        return end_time;
    }

    public void setEnd_time(java.util.Date end_time) {
        this.end_time = end_time;
    }

    public Double getDuration() {
        return duration;
    }

    public void setDuration(Double duration) {
        this.duration = duration;
    }

    public Double getDistance() {
        return distance;
    }

    public void setDistance(Double distance) {
        this.distance = distance;
    }

    public Double getCalories() {
        return calories;
    }

    public void setCalories(Double calories) {
        this.calories = calories;
    }

    public Double getAvg_speed() {
        return avg_speed;
    }

    public void setAvg_speed(Double avg_speed) {
        this.avg_speed = avg_speed;
    }

    public String getRoutes() {
        return routes;
    }

    public void setRoutes(String routes) {
        this.routes = routes;
    }

    public Integer getRank() {
        return rank;
    }

    public void setRank(Integer rank) {
        this.rank = rank;
    }

    public Integer getInvitation() {
        return invitation;
    }

    public void setInvitation(Integer invitation) {
        this.invitation = invitation;
    }



    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
