package com.wistron.swpc.android.WiTMJ.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PERSONAL_INFO".
 */
public class PersonalInfo {

    private Long id;
    /** Not-null value. */
    private String username;
    private Integer tag;
    private String email;
    private String dateOfBirth;
    private Long height;
    private Long weight;
    private String gender;

    public PersonalInfo() {
    }

    public PersonalInfo(Long id) {
        this.id = id;
    }

    public PersonalInfo(Long id, String username, Integer tag, String email, String dateOfBirth, Long height, Long weight, String gender) {
        this.id = id;
        this.username = username;
        this.tag = tag;
        this.email = email;
        this.dateOfBirth = dateOfBirth;
        this.height = height;
        this.weight = weight;
        this.gender = gender;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUsername() {
        return username;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getTag() {
        return tag;
    }

    public void setTag(Integer tag) {
        this.tag = tag;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(String dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Long getHeight() {
        return height;
    }

    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getWeight() {
        return weight;
    }

    public void setWeight(Long weight) {
        this.weight = weight;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

}
